version: "3.9"

services:
  db:
    image: postgres:14.5-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"
  backend:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    restart: always
    volumes:
      - .:/app/backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
  redis:
    image: redis
    restart: always
    command: redis-server
    ports:
      - "6379:6379"
  celery:
    build: .
    command: celery -A expense_manager worker -B
    volumes:
      - .:/app/backend
    depends_on:
      - backend
      - redis
volumes:
  postgres_data: