# Generated by Django 4.1.3 on 2022-11-05 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="type",
        ),
        migrations.AddField(
            model_name="transaction",
            name="is_deposit",
            field=models.BooleanField(default=True, verbose_name="Is deposit"),
        ),
    ]
