# Generated by Django 4.1.3 on 2022-11-05 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0002_remove_transaction_type_transaction_is_deposit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="description",
            field=models.CharField(
                blank=True, max_length=256, null=True, verbose_name="Description"
            ),
        ),
    ]
