# Generated by Django 4.1.3 on 2022-11-05 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="title",
            field=models.CharField(max_length=64, verbose_name="Title"),
        ),
    ]
